// Paw — Tauri application entry point.
// All helper functions (mail, keychain, weather) have been moved to commands:: modules.
// Channel bridge commands are generated by commands::channels::channel_commands! macro.

// ── Paw Atoms (constants, error types) ────────────────────────────────────
pub mod atoms;

// ── Paw Agent Engine ───────────────────────────────────────────────────
pub mod engine;

// ── Paw Command Modules (Systems layer) ───────────────────────────────
pub mod commands;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let engine_state = commands::state::EngineState::new()
        .expect("Failed to initialize Paw Agent Engine");

    tauri::Builder::default()
        .manage(engine_state)
        .plugin(tauri_plugin_log::Builder::new()
            .target(tauri_plugin_log::Target::new(
                tauri_plugin_log::TargetKind::LogDir { file_name: Some("openpawz".into()) },
            ))
            .max_file_size(5_000_000)
            // Global default: only Info+ from third-party crates
            .level(log::LevelFilter::Info)
            // App crate: keep Debug for engine diagnostics
            .level_for("paw_temp", log::LevelFilter::Debug)
            .build())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_process::init())
        .setup(|app| {
            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(10)).await;
                log::info!("[heartbeat] Cron heartbeat started (60s interval)");
                loop {
                    commands::task::run_cron_heartbeat(&app_handle).await;
                    tokio::time::sleep(std::time::Duration::from_secs(60)).await;
                }
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            // ── Mail (himalaya bridge) ──
            commands::mail::write_himalaya_config,
            commands::mail::read_himalaya_config,
            commands::mail::remove_himalaya_account,
            commands::mail::fetch_emails,
            commands::mail::fetch_email_content,
            commands::mail::send_email,
            commands::mail::list_mail_folders,
            commands::mail::move_email,
            commands::mail::delete_email,
            commands::mail::set_email_flag,
            // ── Utility (keychain, weather, db crypto) ──
            commands::utility::keyring_has_password,
            commands::utility::keyring_delete_password,
            commands::utility::fetch_weather,
            commands::utility::get_db_encryption_key,
            commands::utility::has_db_encryption_key,
            commands::utility::check_keychain_health,
            // ── Chat & Sessions ──
            commands::chat::engine_chat_send,
            commands::chat::engine_chat_history,
            commands::chat::engine_chat_abort,
            commands::chat::engine_sessions_list,
            commands::chat::engine_session_rename,
            commands::chat::engine_session_delete,
            commands::chat::engine_session_clear,
            commands::chat::engine_session_cleanup,
            commands::chat::engine_session_compact,
            commands::chat::engine_approve_tool,
            // ── Engine Config & Sandbox ──
            commands::config::engine_sandbox_check,
            commands::config::engine_sandbox_get_config,
            commands::config::engine_sandbox_set_config,
            commands::config::engine_get_config,
            commands::config::engine_get_daily_spend,
            commands::config::engine_set_config,
            commands::config::engine_upsert_provider,
            commands::config::engine_remove_provider,
            commands::config::engine_status,
            commands::config::engine_auto_setup,
            // ── Agent Files (Soul / Persona) ──
            commands::agent::engine_agent_file_list,
            commands::agent::engine_agent_file_get,
            commands::agent::engine_agent_file_set,
            commands::agent::engine_agent_file_delete,
            commands::agent::engine_list_all_agents,
            commands::agent::engine_create_agent,
            commands::agent::engine_delete_agent,
            // ── Memory (Long-term Semantic) ──
            commands::memory::engine_memory_store,
            commands::memory::engine_memory_search,
            commands::memory::engine_memory_stats,
            commands::memory::engine_memory_delete,
            commands::memory::engine_memory_list,
            commands::memory::engine_get_memory_config,
            commands::memory::engine_set_memory_config,
            commands::memory::engine_test_embedding,
            commands::memory::engine_embedding_status,
            commands::memory::engine_embedding_pull_model,
            commands::memory::engine_ensure_embedding_ready,
            commands::memory::engine_memory_backfill,
            // ── Skill Vault ──
            commands::skills::engine_skills_list,
            commands::skills::engine_skill_set_enabled,
            commands::skills::engine_skill_set_credential,
            commands::skills::engine_skill_delete_credential,
            commands::skills::engine_skill_revoke_all,
            commands::skills::engine_skill_get_instructions,
            commands::skills::engine_skill_set_instructions,
            // ── Community Skills (skills.sh) ──
            commands::skills::engine_community_skills_list,
            commands::skills::engine_community_skills_browse,
            commands::skills::engine_community_skills_search,
            commands::skills::engine_community_skill_install,
            commands::skills::engine_community_skill_remove,
            commands::skills::engine_community_skill_set_enabled,
            commands::skills::engine_community_skill_set_agents,
            // ── TOML Manifest Skills (Phase F.1) ──
            commands::skills::engine_toml_skills_scan,
            commands::skills::engine_toml_skill_install,
            commands::skills::engine_toml_skill_uninstall,
            // ── PawzHub Registry (Phase F.4) ──
            commands::skills::engine_pawzhub_search,
            commands::skills::engine_pawzhub_browse,
            commands::skills::engine_pawzhub_install,
            // ── Skill Outputs (Phase F.2) ──
            commands::skills::engine_list_skill_outputs,
            // ── Skill Wizard (Phase F.5) ──
            commands::skill_wizard::engine_wizard_generate_toml,
            commands::skill_wizard::engine_wizard_publish_url,
            // ── Skill Storage (Phase F.6) ──
            commands::skills::engine_skill_store_list,
            // ── Trading ──
            commands::trade::engine_trading_history,
            commands::trade::engine_trading_summary,
            commands::trade::engine_trading_policy_get,
            commands::trade::engine_trading_policy_set,
            // ── Positions (Stop-Loss / Take-Profit) ──
            commands::trade::engine_positions_list,
            commands::trade::engine_position_close,
            commands::trade::engine_position_update_targets,
            // ── Text-to-Speech ──
            commands::tts::engine_tts_speak,
            commands::tts::engine_tts_get_config,
            commands::tts::engine_tts_set_config,
            commands::tts::engine_tts_transcribe,
            // ── Tasks (Kanban Board) ──
            commands::task::engine_tasks_list,
            commands::task::engine_task_create,
            commands::task::engine_task_update,
            commands::task::engine_task_delete,
            commands::task::engine_task_move,
            commands::task::engine_task_activity,
            commands::task::engine_task_set_agents,
            commands::task::engine_task_run,
            commands::task::engine_tasks_cron_tick,
            // ── Channel Bridges (80 commands: 10 channels × 8 ops) ──────────
            // Functions generated by channel_commands! macro in commands/channels.rs.
            // Telegram ──
            commands::channels::engine_telegram_start,
            commands::channels::engine_telegram_stop,
            commands::channels::engine_telegram_status,
            commands::channels::engine_telegram_get_config,
            commands::channels::engine_telegram_set_config,
            commands::channels::engine_telegram_approve_user,
            commands::channels::engine_telegram_deny_user,
            commands::channels::engine_telegram_remove_user,
            // Discord ──
            commands::channels::engine_discord_start,
            commands::channels::engine_discord_stop,
            commands::channels::engine_discord_status,
            commands::channels::engine_discord_get_config,
            commands::channels::engine_discord_set_config,
            commands::channels::engine_discord_approve_user,
            commands::channels::engine_discord_deny_user,
            commands::channels::engine_discord_remove_user,
            // IRC ──
            commands::channels::engine_irc_start,
            commands::channels::engine_irc_stop,
            commands::channels::engine_irc_status,
            commands::channels::engine_irc_get_config,
            commands::channels::engine_irc_set_config,
            commands::channels::engine_irc_approve_user,
            commands::channels::engine_irc_deny_user,
            commands::channels::engine_irc_remove_user,
            // Slack ──
            commands::channels::engine_slack_start,
            commands::channels::engine_slack_stop,
            commands::channels::engine_slack_status,
            commands::channels::engine_slack_get_config,
            commands::channels::engine_slack_set_config,
            commands::channels::engine_slack_approve_user,
            commands::channels::engine_slack_deny_user,
            commands::channels::engine_slack_remove_user,
            // Matrix ──
            commands::channels::engine_matrix_start,
            commands::channels::engine_matrix_stop,
            commands::channels::engine_matrix_status,
            commands::channels::engine_matrix_get_config,
            commands::channels::engine_matrix_set_config,
            commands::channels::engine_matrix_approve_user,
            commands::channels::engine_matrix_deny_user,
            commands::channels::engine_matrix_remove_user,
            // Mattermost ──
            commands::channels::engine_mattermost_start,
            commands::channels::engine_mattermost_stop,
            commands::channels::engine_mattermost_status,
            commands::channels::engine_mattermost_get_config,
            commands::channels::engine_mattermost_set_config,
            commands::channels::engine_mattermost_approve_user,
            commands::channels::engine_mattermost_deny_user,
            commands::channels::engine_mattermost_remove_user,
            // Nextcloud ──
            commands::channels::engine_nextcloud_start,
            commands::channels::engine_nextcloud_stop,
            commands::channels::engine_nextcloud_status,
            commands::channels::engine_nextcloud_get_config,
            commands::channels::engine_nextcloud_set_config,
            commands::channels::engine_nextcloud_approve_user,
            commands::channels::engine_nextcloud_deny_user,
            commands::channels::engine_nextcloud_remove_user,
            // Nostr ──
            commands::channels::engine_nostr_start,
            commands::channels::engine_nostr_stop,
            commands::channels::engine_nostr_status,
            commands::channels::engine_nostr_get_config,
            commands::channels::engine_nostr_set_config,
            commands::channels::engine_nostr_approve_user,
            commands::channels::engine_nostr_deny_user,
            commands::channels::engine_nostr_remove_user,
            // Twitch ──
            commands::channels::engine_twitch_start,
            commands::channels::engine_twitch_stop,
            commands::channels::engine_twitch_status,
            commands::channels::engine_twitch_get_config,
            commands::channels::engine_twitch_set_config,
            commands::channels::engine_twitch_approve_user,
            commands::channels::engine_twitch_deny_user,
            commands::channels::engine_twitch_remove_user,
            // Web Chat ──
            commands::channels::engine_webchat_start,
            commands::channels::engine_webchat_stop,
            commands::channels::engine_webchat_status,
            commands::channels::engine_webchat_get_config,
            commands::channels::engine_webchat_set_config,
            commands::channels::engine_webchat_approve_user,
            commands::channels::engine_webchat_deny_user,
            commands::channels::engine_webchat_remove_user,
            // WhatsApp ──
            commands::channels::engine_whatsapp_start,
            commands::channels::engine_whatsapp_stop,
            commands::channels::engine_whatsapp_status,
            commands::channels::engine_whatsapp_get_config,
            commands::channels::engine_whatsapp_set_config,
            commands::channels::engine_whatsapp_approve_user,
            commands::channels::engine_whatsapp_deny_user,
            commands::channels::engine_whatsapp_remove_user,
            // ── Orchestrator: Projects ──
            commands::project::engine_projects_list,
            commands::project::engine_project_create,
            commands::project::engine_project_update,
            commands::project::engine_project_delete,
            commands::project::engine_project_set_agents,
            commands::project::engine_project_messages,
            commands::project::engine_project_run,
            // ── Browser Profiles & Sandbox ──
            commands::browser::engine_browser_get_config,
            commands::browser::engine_browser_set_config,
            commands::browser::engine_browser_create_profile,
            commands::browser::engine_browser_delete_profile,
            // ── Screenshots ──
            commands::browser::engine_screenshots_list,
            commands::browser::engine_screenshot_get,
            commands::browser::engine_screenshot_delete,
            // ── Per-Agent Workspaces ──
            commands::browser::engine_workspaces_list,
            commands::browser::engine_workspace_files,
            commands::browser::engine_workspace_delete,
            // ── Network Policy (Outbound Domain Allowlist) ──
            commands::browser::engine_network_get_policy,
            commands::browser::engine_network_set_policy,
            commands::browser::engine_network_check_url,

            // ── Tailscale (Remote Access) ──
            commands::tailscale::engine_tailscale_status,
            commands::tailscale::engine_tailscale_get_config,
            commands::tailscale::engine_tailscale_set_config,
            commands::tailscale::engine_tailscale_serve_start,
            commands::tailscale::engine_tailscale_serve_stop,
            commands::tailscale::engine_tailscale_funnel_start,
            commands::tailscale::engine_tailscale_funnel_stop,
            commands::tailscale::engine_tailscale_connect,
            commands::tailscale::engine_tailscale_disconnect,
            // ── Webhook Server (Phase D) ──
            commands::webhook::engine_webhook_start,
            commands::webhook::engine_webhook_stop,
            commands::webhook::engine_webhook_status,
            commands::webhook::engine_webhook_get_config,
            commands::webhook::engine_webhook_set_config,
            commands::webhook::engine_webhook_regenerate_token,
            // ── MCP Servers (Phase E) ──
            commands::mcp::engine_mcp_list_servers,
            commands::mcp::engine_mcp_save_server,
            commands::mcp::engine_mcp_remove_server,
            commands::mcp::engine_mcp_connect,
            commands::mcp::engine_mcp_disconnect,
            commands::mcp::engine_mcp_status,
            commands::mcp::engine_mcp_refresh_tools,
            commands::mcp::engine_mcp_connect_all,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
